# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VA9NDGlYyb3aYK_iLVWpjB0Kc31OTy1K
"""


# IMPORTING DIFFERENT LIBRARIES AND DOWNLOADING STOPWORDS
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from wordcloud import WordCloud


nltk.download('stopwords')

#  DATASET LOAD AND PREVIEW

df = pd.read_csv("twcs.csv", encoding='latin1', on_bad_lines='skip')  # Twitter dataset

df.head()

# Keep only customer messages
df = df[df['inbound'] == True]

# Keep only relevant columns
df = df[['text']].dropna()

df = df.sample(50000)  # reduce size for performance

df.head() # Preview first five rows of the transformed dataset

# DATA CLEANING

# Function to convert text to lower case, remove strings like numbers and remove URL links 
def clean_text(input_text):
    input_text = input_text.lower()
    input_text = re.sub(r"http\S+", "", input_text)   # remove links
    input_text = re.sub(r"[^a-zA-Z]", " ", input_text) # removing anything that is not a letter 
    return input_text

df['cleaned'] = df['text'].apply(clean_text)
df.head()

# REMOVE STOPWORDS

stop_words = set(stopwords.words('english'))

# Defining a function to remove stopwords (irrelevant words) to improve accuracy and reduce noise 
def remove_stopwords(sentence):
    words = sentence.split()
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)

df['processed'] = df['cleaned'].apply(remove_stopwords)

# ASSIGNING SENTIMENT LABELS TO TEACH OUR MODEL

# Simple rule-based labeling for teaching 

def label_sentiment(text):
    negative_words = ['not', 'no', 'delay', 'bad', 'worst', 'issue', 'problem', 'complaint', 'complaining', 'poor', 'difficult']
    
    if any(word in text for word in negative_words):
        return "negative"
    else:
        return "positive"

df['sentiment'] = df['processed'].apply(label_sentiment)

# FEATURE EXTRACTION (TF-IDF)

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df['processed'])
y = df['sentiment']


# TRAIN TEST SPLIT AND MODEL TRAINING

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Choose the Logistic Regression because its good for classification purposes
model = LogisticRegression()
model.fit(X_train, y_train)


# EVALUATION

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

 
# CHURN RISK DEFINITION

def churn_risk(sentiment):
    if sentiment == "negative":
        return "High Risk"
    else:
        return "Low Risk"

df['churn_risk'] = df['sentiment'].apply(churn_risk)

# ===============================
# 11. VISUALIZATION
# ===============================
sns.countplot(x='sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

# ===============================
# 12. WORD CLOUD
# ===============================
negative_text = " ".join(df[df['sentiment'] == "negative"]['processed'])

wordcloud = WordCloud(width=800, height=400).generate(negative_text)

plt.imshow(wordcloud)
plt.axis("off")
plt.title("Common Complaints")
plt.show()
